# Code Generated by Sidekick is for learning and experimentation purposes only.
from __future__ import annotations

import re
import time

import google.generativeai as genai

from config import Settings, get_settings
from logging_config import get_logger

logger = get_logger(__name__)

# Cap how long we're willing to block on a server-suggested retry.
_MAX_BACKOFF_SECONDS = 45.0
_RETRY_DELAY_RE = re.compile(r"retry_delay\s*\{\s*seconds:\s*(\d+)", re.IGNORECASE)


class GeminiError(RuntimeError):
    """Raised when Gemini fails after exhausting retries."""


class QuotaExhaustedError(GeminiError):
    """Raised when a hard (e.g. per-day) quota is exhausted. Not retryable."""


def _parse_retry_delay(message: str) -> float | None:
    match = _RETRY_DELAY_RE.search(message)
    return float(match.group(1)) if match else None


def _is_daily_quota(message: str) -> bool:
    # The per-day free-tier quota id contains "PerDay". Per-minute limits do not.
    return "perday" in message.lower()


def _is_rate_limit(message: str) -> bool:
    lowered = message.lower()
    return "429" in message or "quota" in lowered or "resourceexhausted" in lowered


class GeminiClient:
    def __init__(self, settings: Settings | None = None, max_retries: int = 2) -> None:
        self.settings = settings or get_settings()
        self.max_retries = max_retries
        genai.configure(api_key=self.settings.gemini_api_key)
        self._model = genai.GenerativeModel(self.settings.gemini_model)

    def generate(self, prompt: str, system: str | None = None) -> str:
        """Send a prompt to Gemini and return the plain-text response.

        - On a per-day quota exhaustion: fail fast with QuotaExhaustedError
          (retrying cannot succeed until the quota resets).
        - On a transient/per-minute rate limit: sleep for the server-suggested
          retry_delay (capped) before retrying.
        - On other errors: retry up to max_retries, then raise GeminiError.
        """
        full_prompt = f"{system}\n\n{prompt}" if system else prompt
        attempts = self.max_retries + 1
        last_error: Exception | None = None

        for attempt in range(1, attempts + 1):
            start = time.monotonic()
            try:
                response = self._model.generate_content(full_prompt)
                elapsed_ms = round((time.monotonic() - start) * 1000, 1)
                logger.info(
                    "gemini_generate_success",
                    extra={"attempt": attempt, "elapsed_ms": elapsed_ms},
                )
                return (response.text or "").strip()
            except Exception as exc:  # noqa: BLE001 - SDK boundary, deliberately broad
                elapsed_ms = round((time.monotonic() - start) * 1000, 1)
                last_error = exc
                message = str(exc)
                logger.warning(
                    "gemini_generate_failed",
                    extra={"attempt": attempt, "elapsed_ms": elapsed_ms, "error": message},
                )

                # Hard daily cap: no point retrying today.
                if _is_rate_limit(message) and _is_daily_quota(message):
                    logger.error("gemini_daily_quota_exhausted", extra={"attempt": attempt})
                    raise QuotaExhaustedError(
                        "Gemini daily free-tier quota exhausted; try again after reset."
                    ) from exc

                # Last attempt: don't sleep, just fall through to raise.
                if attempt >= attempts:
                    break

                # Retryable rate limit: honor the server's suggested delay.
                if _is_rate_limit(message):
                    delay = _parse_retry_delay(message)
                    sleep_for = min(delay, _MAX_BACKOFF_SECONDS) if delay else 2.0
                    logger.info("gemini_backoff", extra={"attempt": attempt, "sleep_s": sleep_for})
                    time.sleep(sleep_for)
                else:
                    time.sleep(1.0)  # small backoff for non-rate-limit transients

        raise GeminiError(f"Gemini call failed after {attempts} attempt(s)") from last_error
